server:
  port: 8080

spring:
  application:
    name: order-server
  rabbitmq:
    host: localhost
    port: 5672
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
  data:
    mongodb:
      uri: mongodb://localhost:27017/${MONGO_DB}

order:
  queue: pedidos_fila

grpc:
  server:
    port: 9090

