server:
  port: 8080

spring:
  application:
    name: order-server
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: password

order:
  queue: pedidos_fila

grpc:
  server:
    port: 9090
