server:
  port: 8080

spring:
  application:
    name: order-server
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: password
  data:
    mongodb:
      uri: mongodb://localhost:27017/orderdb

order:
  queue: pedidos_fila

grpc:
  server:
    port: 9090

